version: '3.9'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build:
      context: .
    command: >
      sh -c "python3 manage.py collectstatic --noinput &&
             python3 manage.py migrate &&
             gunicorn url_shortener.wsgi:application --bind 0.0.0.0:8000 --reload"
    expose:
      - 8000
    volumes:
      - .:/code
      - static:/code/static
    depends_on:
      db:
        condition: service_healthy
  proxy:
    build:
      context: ./nginx
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static:/home/app/static
    depends_on:
      web:
        condition: service_started

volumes:
  static:
